### ISSUE TITLE
[Feature Request] Two Finger Swipe to move between images

### ISSUE THREAD

**Issue by LampPrinter** [jdpurcell/qView#1]
:)

**Comment by jdpurcell** [comment]
Implemented in my latest release! I always thought this was a cool feature but never tried to code it until now because it's surprisingly difficult to do properly (e.g. to avoid minor vertical movements at the same time from also zooming). I finally came up with something that seems to work pretty well. Nonetheless it's disabled by default as I consider it experimental, but maybe I'm just overly cautious 😋. In the Settings window, the option is near the bottom of the Images tab.
