### ISSUE TITLE
Image render starts from left when changing from full screen to window

### ISSUE THREAD

**Issue by jordanjay29** [jdpurcell/qView#12]
**Environment:**
- OS: W11
- qView version: 2024-12-08.bea137a

**Information:**
When open in full screen and the image is zoomed in/panned around (often with black "dead" space on the sides), returning to windowed size will display the beginning of the full-screen canvas starting from the left. This can result in the image not appearing in the window render space (panned out of view) until rediscovered with mouse or fit commands again. 

For example, I have qView opening in the center of my monitor. If I open, say, a portrait-sized image in qView and open in full-screen to zoom or pan around, returning to windowed mode will not render the center area as I would expect. Instead it renders the left-most area that was present on the full screen, whether that was the image itself or the dead space of the canvas for zoom/panning. This makes a change from the jurple version where the image would remember the dimensions and location of the windowed frame while in full-screen mode and focus on what was present there when returning to windowed mode.

**Comment by jdpurcell** [comment]
Official qView is very aggressive about auto-fitting or auto-centering the image any time the window is resized which is why it doesn't happen there, but that forced fitting/centering is one of the main things I'm trying to avoid in this fork. I agree it doesn't make sense to keep the top/left position constant when entering/exiting fullscreen or when resizing the window at all for that matter. Honestly I never noticed this before because I always use it with "Constrain image position" enabled, but I want it to work nice/logically even with that disabled. I just made a change makes it maintain the center of the viewport when the window resizes. Basically if you are in fullscreen now, whatever you see in the direct center of the screen will now be in the center of the window when exiting fullscreen. It's still possible to end up with an empty viewport if you had the image panned very far off center in fullscreen, but it should be much better at least. If you'd like to try it, the most recent build is [located here](https://github.com/jdpurcell/qView/actions/runs/12510323412) in the "Artifacts" section.
