### ISSUE TITLE
Keybinds to move the view/image

### ISSUE THREAD

**Issue by Salted-Bread** [jdpurcell/qView#2]
In the original qView you can press CTRL + Arrowkeys to move the view around in the image, which is helpful for when you're zoomed in. In this fork the keybinds do not seem to work. I can only move the view around using the mouse.

Any chance this can be added/fixed?

**Comment by jdpurcell** [comment]
Oh, yeah, I had removed that because it didn't work with the "constrain image position" feature and honestly I thought nobody used it 😄. I just figured out how to make the features compatible, though, so you can try the [latest build here](https://github.com/jdpurcell/qView/actions/runs/6216150125) which should work!
