### ISSUE TITLE
Latest release `v2024-05-23.24cc85a` is marked as `pre-release`?

### ISSUE THREAD

**Issue by Hrxn** [jdpurcell/qView#4]
The most recent release/tag
https://github.com/jdpurcell/qView/releases/tag/v2024-05-23.24cc85a

Is listed as a "pre-release", instead of a regular "Latest" release - without mentioning anything with regard to being released specifically for testing purposes or something.

Is this really intentional? Not "safe" for general usage?

**Comment by jdpurcell** [comment]
The story is, someone requested a feature "macOS: Option to reuse existing window when launching with image", but I don't know whether they have a GitHub account, and the GitHub Actions artifacts are only available when signed in. I made the release so they could download it, but marked as pre-release so it doesn't trigger an update notification inside qView if update checks are enabled.

But it's safe/stable, no worries! I just didn't want to cause an update notification yet, because I might add another small feature soon. Actually I wanted to add a "Skip this version" button in the update notification dialog. Right now it will re-prompt upon startup if it's been more than 4 hours since the last check/notification.

**Comment by Hrxn** [comment]
Okay, thank you, I understand.
