### ISSUE TITLE
Toggle between Original size and Fit to window on mouse botton

### ISSUE THREAD

**Issue by Thespikedballofdoom** [jdpurcell/qView#6]
Basically an option which toggles between original and fitted views for the image. Original Qview does this and with when the "I had just installed another program called X-Mouse Button Control to remap the middle mouse button in it only to send my binding for it which made it act like a toggle, but when I found this fork shortly after I was hoping it could be the same kind of thing.

**Comment by jdpurcell** [comment]
Yes as you noticed, I made "Original Size" simply reset zoom to 100% instead of functioning like a quasi-toggle in official qView. That is intentional as I found the way "Original Size" works in official qView to be confusing and unintuitive; not just the toggle part, but the fact that once you're in "Original Size" mode, even if you zoom in/out, it's still kind of stuck in that mode and alters certain behaviors.

Anyway I just added a secret option for this, not even in the settings UI. I don't want to make a new "release" yet but if you'd like to try it, the build from GitHub Actions is [here](https://github.com/jdpurcell/qView/actions/runs/9883594168/artifacts/1688958332). The option can only be enabled via the Registry, which you can accomplish by running this in a command prompt:
`reg add HKEY_CURRENT_USER\SOFTWARE\qView\qView-JDP\options /v originalsizeastoggle /f /t REG_SZ /d
 true`

Or if any macOS users see this in the future and want to try it, the command is:
`defaults write com.qview.qView-JDP options.originalsizeastoggle -bool TRUE`

**Comment by Thespikedballofdoom** [comment]
I sadly can't seem to make it work

**Comment by jdpurcell** [comment]
I should mention, the toggle is between original size and whatever the "Zoom default" setting is (Settings->Image section), so if you have that set to "Zoom to FIt" it should work, but if the default is "Original Size" it won't do anything.

Otherwise you might double check that the setting is present in the right place. It should be inside the HKEY_CURRENT_USER\SOFTWARE\qView\\**qView-JDP**\\options section, noting that this fork keeps its settings separate from the official version to prevent incompatibilities.
![Screenshot 2024-07-13 123206](https://github.com/user-attachments/assets/c9562daa-242e-4b29-b03f-3416bfd1cb27)

**Comment by Thespikedballofdoom** [comment]
I see, I apparently still have whiplash from transferring to qview and did have it set to original size, and the image viewer I used before qView the bind would repeat the toggle forever and I tended to use it as a no-keyboard reset-the-scale button in addition to just checking back and forth.
I can keep using my XBMC bind to do this if it's a hassle though.

**Comment by jdpurcell** [comment]
If I understand correctly, you want the zoom default to be "original size" and still allow a toggle behavior? If so I just did that in the latest build [here](https://github.com/jdpurcell/qView/actions/runs/9921671400/artifacts/1698213846).

**Comment by Thespikedballofdoom** [comment]
I have to click twice strangely (on either default Original or default Zoom to fit) but it does toggle now, thanks a bunch.

**Comment by jdpurcell** [comment]
> rapidly clicking seems to not pick up well

Yeah some of the events get delivered as "double click" instead of a normal click in that case. I just worked around that in the [latest build](https://github.com/jdpurcell/qView/actions/runs/9921890201/artifacts/1698248010) so it should work even when rapidly clicking.

**Comment by Thespikedballofdoom** [comment]
Perfection. thank you a million
